name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10.2.0

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
        env:
          NODE_ENV: production

      - name: Install ESLint dependencies
        run: pnpm add -D @eslint/js eslint-config-prettier eslint-plugin-unicorn typescript-eslint eslint@9

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test
        env:
          NODE_ENV: test
